[network]
name = "devnet"

[accounts.deployer]
mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply writer small concern"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay"
balance = 100_000_000_000_000

[accounts.wallet_3]
mnemonic = "cycle puppet frog tornado change embarrass negative admit college outdoor diamond expect hire pluck fiber electric okay appear spell book occur brave report"
balance = 100_000_000_000_000

[devnet]
pox_stacking_orders = []
