;; credential-marketplace.clar
;; Errors: u100 not-authorized, u101 not-found, u102 exists, u103 insufficient-payment, u104 already-purchased
(define-constant CONTRACT-OWNER tx-sender)
(define-constant FEE-BPS u250)
(define-map listings { listing-id: uint } { seller: principal, credential-hash: (buff 32), price: uint, active: bool, schema: (string-ascii 40) })
(define-map purchases { listing-id: uint, buyer: principal } { block: uint })
(define-data-var listing-nonce uint u0)
(define-public (list-credential (credential-hash (buff 32)) (price uint) (schema (string-ascii 40)))
  (let ((id (+ (var-get listing-nonce) u1))) (var-set listing-nonce id)
  (ok (map-set listings { listing-id: id } { seller: tx-sender, credential-hash: credential-hash, price: price, active: true, schema: schema }))))
(define-public (buy-credential (listing-id uint))
  (let ((l (unwrap! (map-get? listings { listing-id: listing-id }) (err u101))) (fee (/ (* (get price l) FEE-BPS) u10000)))
  (asserts! (get active l) (err u101))
  (asserts! (is-none (map-get? purchases { listing-id: listing-id, buyer: tx-sender })) (err u104))
  (try! (stx-transfer? (- (get price l) fee) tx-sender (get seller l)))
  (try! (stx-transfer? fee tx-sender CONTRACT-OWNER))
  (map-set purchases { listing-id: listing-id, buyer: tx-sender } { block: block-height })
  (ok true)))
(define-public (delist-credential (listing-id uint))
  (let ((l (unwrap! (map-get? listings { listing-id: listing-id }) (err u101))))
  (asserts! (is-eq tx-sender (get seller l)) (err u100))
  (ok (map-set listings { listing-id: listing-id } (merge l { active: false })))))
(define-read-only (get-listing (id uint)) (map-get? listings { listing-id: id }))
(define-read-only (has-purchased? (id uint) (buyer principal)) (is-some (map-get? purchases { listing-id: id, buyer: buyer })))