;; credential-transfer.clar
;; Errors: u100 not-authorized, u101 not-transferable, u102 not-holder, u103 not-found
(define-constant CONTRACT-OWNER tx-sender)
(define-map transfer-policies { schema: (string-ascii 40) } { transferable: bool, max-transfers: uint })
(define-map credentials { credential-id: uint } { schema: (string-ascii 40), holder: principal, issuer: principal, transfers: uint, revoked: bool })
(define-data-var cred-nonce uint u0)
(define-public (set-transfer-policy (schema (string-ascii 40)) (transferable bool) (max-transfers uint))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100)) (ok (map-set transfer-policies { schema: schema } { transferable: transferable, max-transfers: max-transfers }))))
(define-public (issue-credential (holder principal) (schema (string-ascii 40)))
  (let ((id (+ (var-get cred-nonce) u1))) (var-set cred-nonce id)
  (ok (map-set credentials { credential-id: id } { schema: schema, holder: holder, issuer: tx-sender, transfers: u0, revoked: false }))))
(define-public (transfer-credential (credential-id uint) (to principal))
  (let ((c (unwrap! (map-get? credentials { credential-id: credential-id }) (err u103))) (p (unwrap! (map-get? transfer-policies { schema: (get schema c) }) (err u101))))
  (asserts! (is-eq tx-sender (get holder c)) (err u102)) (asserts! (get transferable p) (err u101)) (asserts! (< (get transfers c) (get max-transfers p)) (err u101))
  (ok (map-set credentials { credential-id: credential-id } (merge c { holder: to, transfers: (+ (get transfers c) u1) })))))
(define-read-only (get-credential (id uint)) (map-get? credentials { credential-id: id }))
(define-read-only (is-transferable? (schema (string-ascii 40))) (match (map-get? transfer-policies { schema: schema }) p (get transferable p) false))