;; governance-v2.clar — weighted voting with quorum
;; Errors: u100 not-authorized, u101 not-found, u102 already-voted, u103 voting-closed, u104 quorum-not-met, u105 already-executed
(define-constant CONTRACT-OWNER tx-sender)
(define-constant VOTING-PERIOD u1440)
(define-constant QUORUM-BPS u3000)
(define-map proposals { proposal-id: uint } { title: (string-ascii 80), proposer: principal, for-weight: uint, against-weight: uint, start-block: uint, end-block: uint, executed: bool })
(define-map votes { proposal-id: uint, voter: principal } { weight: uint, support: bool })
(define-map staking-weights principal uint)
(define-data-var proposal-nonce uint u0)
(define-data-var total-staked uint u0)
(define-public (set-staking-weight (voter principal) (weight uint))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100))
  (var-set total-staked (+ (var-get total-staked) weight))
  (ok (map-set staking-weights voter weight))))
(define-public (create-proposal (title (string-ascii 80)))
  (let ((id (+ (var-get proposal-nonce) u1))) (var-set proposal-nonce id)
  (ok (map-set proposals { proposal-id: id } { title: title, proposer: tx-sender, for-weight: u0, against-weight: u0, start-block: block-height, end-block: (+ block-height VOTING-PERIOD), executed: false }))))
(define-public (cast-vote (proposal-id uint) (support bool))
  (let ((p (unwrap! (map-get? proposals { proposal-id: proposal-id }) (err u101))) (w (default-to u1 (map-get? staking-weights tx-sender))))
  (asserts! (<= block-height (get end-block p)) (err u103))
  (asserts! (is-none (map-get? votes { proposal-id: proposal-id, voter: tx-sender })) (err u102))
  (map-set votes { proposal-id: proposal-id, voter: tx-sender } { weight: w, support: support })
  (ok (map-set proposals { proposal-id: proposal-id } (merge p (if support { for-weight: (+ (get for-weight p) w), against-weight: (get against-weight p) } { for-weight: (get for-weight p), against-weight: (+ (get against-weight p) w) }))))))
(define-public (execute-proposal (proposal-id uint))
  (let ((p (unwrap! (map-get? proposals { proposal-id: proposal-id }) (err u101))))
  (asserts! (not (get executed p)) (err u105)) (asserts! (> block-height (get end-block p)) (err u103))
  (let ((total (+ (get for-weight p) (get against-weight p))) (needed (/ (* (var-get total-staked) QUORUM-BPS) u10000)))
  (asserts! (>= total needed) (err u104)) (asserts! (> (get for-weight p) (get against-weight p)) (err u104))
  (ok (map-set proposals { proposal-id: proposal-id } (merge p { executed: true }))))))
(define-read-only (get-proposal (id uint)) (map-get? proposals { proposal-id: id }))
(define-read-only (get-vote (id uint) (voter principal)) (map-get? votes { proposal-id: id, voter: voter }))