;; oracle-v2.clar
;; Errors: u100 not-authorized, u101 not-found, u102 stale, u103 insufficient-sources
(define-constant CONTRACT-OWNER tx-sender)
(define-constant STALE-BLOCKS u20)
(define-constant MIN-SOURCES u2)
(define-map feeders principal { active: bool, submissions: uint })
(define-map price-feeds { asset: (string-ascii 10), feeder: principal } { price: uint, submitted-at: uint })
(define-map aggregated-prices { asset: (string-ascii 10) } { price: uint, sources: uint, updated-at: uint })
(define-public (authorize-feeder (f principal))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100)) (ok (map-set feeders f { active: true, submissions: u0 }))))
(define-public (submit-price (asset (string-ascii 10)) (price uint))
  (let ((f (unwrap! (map-get? feeders tx-sender) (err u100))))
  (asserts! (get active f) (err u100))
  (map-set price-feeds { asset: asset, feeder: tx-sender } { price: price, submitted-at: block-height })
  (map-set feeders tx-sender (merge f { submissions: (+ (get submissions f) u1) }))
  (ok price)))
(define-public (aggregate-price (asset (string-ascii 10)) (prices (list 5 uint)))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100)) (asserts! (>= (len prices) MIN-SOURCES) (err u103))
  (let ((median (unwrap! (element-at prices (/ (len prices) u2)) (err u103))))
  (map-set aggregated-prices { asset: asset } { price: median, sources: (len prices), updated-at: block-height })
  (ok median))))
(define-read-only (get-price (asset (string-ascii 10)))
  (match (map-get? aggregated-prices { asset: asset })
    f (if (<= (- block-height (get updated-at f)) STALE-BLOCKS) (ok (get price f)) (err u102))
    (err u101)))
(define-read-only (get-feeder-submissions (f principal)) (match (map-get? feeders f) d (get submissions d) u0))