;; proof-certification.clar
;; Errors: u100 not-authorized, u101 not-found, u102 cert-exists, u103 invalid-tier
(define-constant CONTRACT-OWNER tx-sender)
(define-map certified-issuers principal { tier-limit: uint, issued: uint })
(define-map certifications { proof-hash: (buff 32) } { issuer: principal, tier: (string-ascii 16), certified-at: uint, metadata-uri: (string-ascii 128) })
(define-data-var total-certifications uint u0)
(define-public (add-issuer (issuer principal) (tier-limit uint))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100)) (ok (map-set certified-issuers issuer { tier-limit: tier-limit, issued: u0 }))))
(define-public (certify (proof-hash (buff 32)) (tier (string-ascii 16)) (metadata-uri (string-ascii 128)))
  (let ((id (unwrap! (map-get? certified-issuers tx-sender) (err u100))))
  (asserts! (is-none (map-get? certifications { proof-hash: proof-hash })) (err u102))
  (map-set certifications { proof-hash: proof-hash } { issuer: tx-sender, tier: tier, certified-at: block-height, metadata-uri: metadata-uri })
  (map-set certified-issuers tx-sender (merge id { issued: (+ (get issued id) u1) }))
  (var-set total-certifications (+ (var-get total-certifications) u1)) (ok proof-hash)))
(define-public (revoke-certification (proof-hash (buff 32)))
  (let ((c (unwrap! (map-get? certifications { proof-hash: proof-hash }) (err u101))))
  (asserts! (is-eq tx-sender (get issuer c)) (err u100))
  (ok (map-delete certifications { proof-hash: proof-hash }))))
(define-read-only (get-certification (h (buff 32))) (map-get? certifications { proof-hash: h }))
(define-read-only (get-issuer-stats (i principal)) (map-get? certified-issuers i))