;; referral-reward.clar
;; Errors: u100 not-authorized, u101 already-claimed, u102 insufficient-pool, u103 no-referrals
(define-constant CONTRACT-OWNER tx-sender)
(define-constant REWARD-PER-REFERRAL u100000)
(define-constant MAX-TIER u5)
(define-map claimed-rewards principal { amount: uint, claimed-at: uint })
(define-map reward-tiers uint uint)
(define-data-var reward-pool uint u0)
(define-public (fund-pool (amount uint))
  (begin (try! (stx-transfer? amount tx-sender (as-contract tx-sender))) (var-set reward-pool (+ (var-get reward-pool) amount)) (ok amount)))
(define-public (set-tier-multiplier (count uint) (mult uint))
  (begin (asserts! (is-eq tx-sender CONTRACT-OWNER) (err u100)) (asserts! (<= mult MAX-TIER) (err u100)) (ok (map-set reward-tiers count mult))))
(define-public (claim-rewards (referral-count uint))
  (let ((mult (default-to u1 (map-get? reward-tiers referral-count))) (reward (* REWARD-PER-REFERRAL (min mult MAX-TIER))))
  (asserts! (> referral-count u0) (err u103))
  (asserts! (is-none (map-get? claimed-rewards tx-sender)) (err u101))
  (asserts! (>= (var-get reward-pool) reward) (err u102))
  (try! (as-contract (stx-transfer? reward tx-sender tx-sender)))
  (var-set reward-pool (- (var-get reward-pool) reward))
  (map-set claimed-rewards tx-sender { amount: reward, claimed-at: block-height })
  (ok reward)))
(define-read-only (get-pool-balance) (var-get reward-pool))
(define-read-only (has-claimed? (a principal)) (is-some (map-get? claimed-rewards a)))