;; referral-reward.clar
;; Errors: u100 not-authorized, u101 not-found, u102 already-exists, u103 invalid-input
(define-constant CONTRACT-OWNER tx-sender)
(define-map referral_reward_entries { entry-id: uint } { owner: principal, value: (buff 32), block: uint, active: bool })
(define-data-var entry-nonce uint u0)
(define-data-var total-entries uint u0)
(define-public (add-entry (value (buff 32)))
  (let ((id (+ (var-get entry-nonce) u1)))
    (var-set entry-nonce id)
    (var-set total-entries (+ (var-get total-entries) u1))
    (ok (map-set referral_reward_entries { entry-id: id } { owner: tx-sender, value: value, block: block-height, active: true }))))
(define-public (deactivate-entry (id uint))
  (let ((e (unwrap! (map-get? referral_reward_entries { entry-id: id }) (err u101))))
    (asserts! (is-eq tx-sender (get owner e)) (err u100))
    (ok (map-set referral_reward_entries { entry-id: id } (merge e { active: false })))))
(define-public (update-entry (id uint) (value (buff 32)))
  (let ((e (unwrap! (map-get? referral_reward_entries { entry-id: id }) (err u101))))
    (asserts! (is-eq tx-sender (get owner e)) (err u100))
    (ok (map-set referral_reward_entries { entry-id: id } (merge e { value: value })))))
(define-read-only (get-entry (id uint)) (map-get? referral_reward_entries { entry-id: id }))
(define-read-only (get-total) (var-get total-entries))