;; referral-registry.clar
;; Errors: u100 already-registered, u101 self-referral, u102 not-found, u103 not-authorized
(define-constant CONTRACT-OWNER tx-sender)
(define-constant REWARD-AMOUNT u50000)
(define-map referrals principal { referrer: principal, block: uint, rewarded: bool })
(define-map referral-counts principal uint)
(define-public (register-referral (referrer principal))
  (begin (asserts! (not (is-eq tx-sender referrer)) (err u101))
  (asserts! (is-none (map-get? referrals tx-sender)) (err u100))
  (map-set referrals tx-sender { referrer: referrer, block: block-height, rewarded: false })
  (map-set referral-counts referrer (+ (default-to u0 (map-get? referral-counts referrer)) u1))
  (ok true)))
(define-public (claim-referral-reward (referee principal))
  (let ((r (unwrap! (map-get? referrals referee) (err u102))))
  (asserts! (is-eq tx-sender (get referrer r)) (err u103))
  (asserts! (not (get rewarded r)) (err u103))
  (map-set referrals referee (merge r { rewarded: true }))
  (ok REWARD-AMOUNT)))
(define-read-only (get-referrer (a principal)) (map-get? referrals a))
(define-read-only (get-referral-count (a principal)) (default-to u0 (map-get? referral-counts a)))
(define-read-only (is-referred? (a principal)) (is-some (map-get? referrals a)))